swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get Transactions
      description: Get all transactions for the current month for a specific account of a user. Only accessible to the authenticated user.
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionList'
        '400':
          description: Invalid Request
        '403':
          description: User does not have access to the requested transactions
        '500':
          description: Internal Server Error

  /user/accounts/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get Transaction Details
      description: Get details of a specific transaction for a specific account of a user. Only accessible to the authenticated user.
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Request
        '403':
          description: User does not have access to the requested transaction
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /user/accounts/transactions/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update Category
      description: Update the categorie of a specific transaction for a specific account of a user. Only accessible to the authenticated user.
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Updated transaction information
          required: true
          schema:
            $ref: '#/definitions/categoryUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction information updated successfully
          schema:
            $ref: '#/definitions/categoryUpdateResponse'
        '400':
          description: Invalid Request
        '403':
          description: User does not have access to the requested transaction
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /user/accounts/transactions/{transactionId}/note:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update Note
      description: Update a note for a specific transaction for a specific account of a user. Only accessible to the authenticated user.
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction
          required: true
          type: string
        - in: body
          name: body
          description: Updated note
          required: true
          schema:
            $ref: '#/definitions/note'
      produces:
        - application/json
      responses:
        '200':
          description: note updated successfully
        '400':
          description: Invalid Request
        '403':
          description: User does not have access to the requested transactions
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      note:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  TransactionList:
    type: array
    items:
      $ref: '#/definitions/TransactionListDetails'
  TransactionListDetails:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: string
      amount:
        type: number
      date:
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: string
      amount:
        type: number
      date:
        type: string
      category:
        type: string
      note:
        type: string
  categoryUpdate:
    type: object
    properties:
      category:
        type: string
  categoryUpdateResponse:
    type: object
    properties:
      status:
        type: integer
      note:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
          transactionId:
            type: string
          category:
            type: string
  note:
    type: object
    properties:
      note:
        type: string
